name: eslint

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/eslint.yml'
      - 'academic-credentials/react/**'
      - 'academic-calendar/react/**'
  pull_request:
    branches: [main]

jobs:
  eslint-academic-credentials-react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: cd academic-credentials/react && yarn install && yarn run lint
  eslint-academic-calendar-react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: cd academic-calendar/react && yarn install && yarn run lint
