name: eslint
on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/eslint.yml"
      - "react/**"
  pull_request:
    branches: [main]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install --prefix react
      - run: npx eslint **/*.jsx 
